version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./db-backend/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./db-backend/01-sample_records.sql:/docker-entrypoint-initdb.d/01-sample_records.sql
    environment:
      - POSTGRES_DB=catan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  app:
    build: ./db-backend
    container_name: app
    environment:
      - POSTGRES_DB=catan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/catan
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - app
